### ISSUE TITLE
[Improvements] properties prefix, localization table name, text field placeholder property

### ISSUE THREAD

**Issue by DZamataev** [nthegedus/NHLocalize#1]
Hi and thanks for sharing such a good solution!
Could you please pay attention to the following improvements:
1. Prefix all property names declared in your categories in order to exclude property name collision possibility and conform to modern Obj-C standards.
   So for `UILabel+NHLocalize` category
   `@property (nonatomic, copy) NSString *localize;` 
   would become 
   `@property (nonatomic, copy) NSString *nhl_text;`
2. Add property to specify localization table name and use 
   `NSLocalizedStringFromTable(keyLocalize, self.nhl_localizationTableName, nil)` 
   when this property is set (not nil) instead of 
   `NSLocalizedString(keyLocalize, nil)`
3. Make it possible to localize UITextField `placeholder` property in your category.

**Comment by DZamataev** [comment]
Thanks for accepting and working on suggested improvements!

You did change:

```
 -(NSString *)nhlButton {
      return self.titleLabel.text;
  }

-(void)setNhlButton:(NSString *)nhlButton {
      [self setTitle:NSLocalizedString(nhlButton, nil) forState:UIControlStateNormal];
  }
```

perhaps `nhlButton` is not the best name. Actually `UIButton` can have several localized titles for different `UIControlState`s. So i suppose it's better to name them `nhl_normalTitle`, `nhl_highlightedTitle`, `nhl_selectedTitle` e.t.c.
Link to the style guide: http://google-styleguide.googlecode.com/svn/trunk/objcguide.xml?showone=Category_Names#Category_Names

**Comment by nthegedus** [comment]
Done!

Thanks for your suggestions DZamataev.
